.PHONY: test race vet fmt check-fmt examples integration-compile check

test:
	go test ./...

race:
	go test -race ./...

vet:
	go vet ./...
	cd examples/pgx && GOWORK=off go vet -mod=readonly ./...
	cd examples/sql && GOWORK=off go vet -mod=readonly ./...
	cd examples/bun && GOWORK=off go vet -mod=readonly ./...

fmt:
	gofmt -w .

check-fmt:
	@test -z "$$(gofmt -l .)" || \
		(echo 'Run make fmt to format Go files'; exit 1)

examples:
	go test ./examples/...
	cd examples/pgx && GOWORK=off go test -mod=readonly ./...
	cd examples/sql && GOWORK=off go test -mod=readonly ./...
	cd examples/bun && GOWORK=off go test -mod=readonly ./...

integration-compile:
	go test -tags=integration -run '^$$' ./test/integration

check: check-fmt race vet examples integration-compile
